services:
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks: 
  app-network:
    external: false